blank_issues_enabled: false
contact_links:
  - name: ❓ openmsa IDP Community Slack
    url: https://join.slack.com/t/openmsa-idp/shared_invite/zt-1pxtehxom-fCFtF9rRe3vFqUiFFeAkmg
    about: Please ask and answer questions here.
